services:
  roland-pc:
    build:
      context: .
      args:
        ROS_DISTRO: jazzy
    image: roland-pc:jazzy
    container_name: roland-pc
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    entrypoint: /roland/bringup/pc/entrypoint.sh
    volumes:
      - ${REPO_ROOT}:/roland
    command: ros2 launch /roland/bringup/pc/joy.launch.py
